config/routes.rb
Rails.application.routes.draw do
  get 'user_transactions/listAll'
  get 'user_transactions/vote'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'user_transactions#listAll'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cause.rb
class Cause < ApplicationRecord
  has_many :users
  has_many :payments
end

app/models/payment.rb
class Payment < ApplicationRecord
  belongs_to :cause
  has_many :vote
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :cause
  has_many :vote
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :payment
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def hello
      render html: "Ali smells"
  end
end

app/controllers/user_transactions_controller.rb
class UserTransactionsController < ApplicationController
  #Permanant address for the test api merchant
  TEST_MERCH_ID = "58a8e6251756fc834d9053df"

  def listAll
    @payments = Payment.all
    @uid = params[:uid]
  end

  def vote
    val = params[:val]
    uid = params[:uid]
    payid = params[:payid]
    v = Vote.all.where(user_id:uid, payment_id:payid).first
    if v
      v.value = val
      v.save
    else
      v = Vote.create(value:val, user_id:uid, payment_id:payid)
    end
    p = v.payment
    if (1.0 * p.vote.where(value:1).count / p.cause.users.count) > 0.50
      Purchase.createPurchase(p.cause.accid,
                              {"merchant_id": TEST_MERCH_ID,
                               "medium": "balance",
                               "amount": p.amt,
                               "description": p.desc});0
      flash.notice = 'Successfully made purchase: "' + p.title + '" to merchant id ' + TEST_MERCH_ID
    end
    redirect_to root_url(:uid=>(uid.to_i+1).to_s)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_transactions_helper.rb
module UserTransactionsHelper
  def get_up_percent(payment)
    if payment.vote.first
      "%.2f%%" % (100.0 * payment.vote.where(value: 1).count / payment.cause.users.count)
    end
  end
  def get_down_percent(payment)
    if payment.vote.first
      "%.2f%%" % (100.0 * payment.vote.where(value: -1).count / payment.cause.users.count)
    end
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Untitled</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/user_transactions/listAll.html.erb
<% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
<% end %>
<% @payments.each do |transaction|%>
  <button class="accordion"><%= transaction.title %> - $<%= "%.2f" % transaction.amt %></button>
  <div class="panel">
    <h3><%= transaction.desc %></h3>
    <p>In favor: <%= get_up_percent transaction %>
      <%= link_to "Approve", user_transactions_vote_path(payid:transaction.id, uid:@uid, val:1), :id=>"upvote-btn", :class=>"vote up"%></p>
    <p>Against: <%= get_down_percent transaction %>
      <%= link_to "Disapprove", user_transactions_vote_path(payid:transaction.id, uid:@uid, val:-1), :id=>"downvote-btn", :class=>"vote down"%></p>
  </div>
<% end %>